 
import React, { useEffect, useRef, useState } from "react";
import { useParams, Link, useLocation } from "react-router-dom";
import api from "../api";

export default function ChatPage() {
  const { caseId } = useParams();
  const location = useLocation();
  const caseFromState = location.state?.caseData;
  const patientId = location.state?.patientId;

  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [caseInfo, setCaseInfo] = useState(caseFromState || null);
  const [treatmentPlan, setTreatmentPlan] = useState(
    caseFromState?.treatmentPlan || ""
  );

  const messagesEndRef = useRef(null);

  useEffect(() => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({ behavior: "smooth" });
    }
  }, [messages]);

  // Load existing messages from database when component mounts
  useEffect(() => {
    const loadMessages = async () => {
      try {
        const res = await api.get(`/cases/messages/${caseId}`);
        const loadedMessages = res.data.map((m) => ({
          sender: m.sender,
          content: m.content,
        }));
        setMessages(loadedMessages);
        
        // Update treatment plan from the latest AI message if available
        const latestAiMessage = res.data
          .filter((m) => m.sender === "ai")
          .pop();
        if (latestAiMessage && !treatmentPlan) {
          setTreatmentPlan(latestAiMessage.content);
        }
      } catch (err) {
        console.error("Failed to load messages:", err);
        // Don't show error to user, just start with empty messages
      }
    };

    if (caseId) {
      loadMessages();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [caseId]);

  const handleSend = async (e) => {
    e.preventDefault();
    if (!input.trim()) return;
    const doctorMessage = { sender: "doctor", content: input };

    setMessages((prev) => [...prev, doctorMessage]);
    setInput("");
    setLoading(true);
    setError("");

    try {
      const res = await api.post(`/cases/ai/${caseId}`, {
        message: doctorMessage.content,
      });
      const aiMessage = { sender: "ai", content: res.data.aiText };
      setMessages((prev) => [...prev, aiMessage]);
      setTreatmentPlan(res.data.aiText || "");
    } catch (err) {
      console.error(err);
      setError("Failed to get AI response");
    } finally {
      setLoading(false);
    }
  };

  const backHref = patientId
    ? `/patients/${patientId}/cases`
    : "/patients";

  return (
    <div className="page-card">
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "0.5rem",
        }}
      >
        <Link to={backHref}>&lt; Back to Cases</Link>
      </div>

      <h2 style={{ marginTop: 0, marginBottom: "0.25rem" }}>
        {caseInfo?.title || `Case #${caseId}`}
      </h2>
      <p
        style={{
          marginTop: 0,
          marginBottom: "0.75rem",
          fontSize: "0.9rem",
          color: "#4b5563",
        }}
      >
        Status: <strong>{caseInfo?.status || "open"}</strong>
      </p>
      <p
        style={{
          marginTop: 0,
          marginBottom: "1rem",
          fontSize: "0.9rem",
          color: "#6b7280",
        }}
      >
        Chat with the AI assistant about this case. Treatment plans generated by
        the AI are automatically saved to this case.
      </p>
      {error && <p style={{ color: "red" }}>{error}</p>}

      <div
        style={{
          border: "1px solid #e5e7eb",
          borderRadius: "0.5rem",
          padding: "0.75rem",
          marginBottom: "0.75rem",
          background: "#f9fafb",
          maxHeight: "280px",
          overflowY: "auto",
        }}
      >
        {messages.length === 0 && (
          <p style={{ color: "#777" }}>
            No messages yet. Describe the patient&apos;s symptoms to begin.
          </p>
        )}
        {messages.map((m, idx) => (
          <div
            key={idx}
            style={{
              marginBottom: "0.5rem",
              textAlign: m.sender === "doctor" ? "right" : "left",
            }}
          >
            <div
              style={{
                display: "inline-block",
                padding: "0.35rem 0.65rem",
                borderRadius: "999px",
                backgroundColor:
                  m.sender === "doctor" ? "#dbeafe" : "#dcfce7",
              }}
            >
              <strong style={{ marginRight: "0.35rem" }}>
                {m.sender === "doctor" ? "You" : "AI"}:
              </strong>
              <span>{m.content}</span>
            </div>
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>

      <form onSubmit={handleSend} style={{ marginBottom: "1rem" }}>
        <div className="form-group">
          <label htmlFor="chat-input">Message to AI</label>
          <textarea
            id="chat-input"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Describe symptoms, history, or questions for the AI..."
            rows={3}
            style={{ width: "100%", resize: "vertical" }}
          />
        </div>
        <button type="submit" disabled={loading}>
          {loading ? "Sending..." : "Send to AI"}
        </button>
      </form>

      <div
        style={{
          borderTop: "1px solid #e5e7eb",
          paddingTop: "0.75rem",
        }}
      >
        <h3 style={{ marginTop: 0, marginBottom: "0.35rem" }}>
          Auto-saved Treatment Plan
        </h3>
        {treatmentPlan ? (
          <div
            style={{
              background: "#f9fafb",
              borderRadius: "0.5rem",
              padding: "0.75rem",
              whiteSpace: "pre-wrap",
              fontSize: "0.9rem",
            }}
          >
            {treatmentPlan}
          </div>
        ) : (
          <p style={{ color: "#9ca3af", fontSize: "0.9rem" }}>
            No treatment plan generated yet. Once the AI responds, the latest
            plan will appear here.
          </p>
        )}
      </div>
    </div>
  );
}
